---
title: "判決書整理"
output: html_notebook
---

```{r}
library(readxl)
library(writexl)
library(data.table)
library(stringr)
```
Step 1. 讀取判決書檔案，並結合成一個表格。
```{r}
path <- "E:/python/verdict_download/"
name <- list.files(paste0(path,"primary_result"))
data <- NULL
data <- lapply(name,function(x){
  as.data.table(read_xlsx(
    paste0(path,"primary_result/",x)))
})
all_data <- rbindlist(data)

```
Step 2. 梳理判決書內容
基本梳理


```{r}
#去除掉"裁定"
all_data <- all_data[!grep("裁定",article_code)]
all_data <- unique(all_data, by = "url")
all_data[,full_text:=gsub(",","，",full_text)]
data_deal <- NULL
data_deal <- all_data

data_deal[,test_text:=full_text]
data_deal[,test_text:=gsub("\\r","\n",test_text)]#將enter統一為換行符號
data_deal[,test_text:=gsub("\\n\\d{1,3}\\n\\n","",test_text)]#將行號取代到
data_deal[,test_text:=gsub("\\n\\n\\n    ","",test_text)]#將換行與四個空格取代掉
data_deal[,test_text:=gsub("\\n{2,3}","\n",test_text)]#將2-3個換行符號取代成一個
data_deal[,test_text:=gsub(" {4,}","",test_text)]#取代掉4個以上的空格


write_xlsx(data_deal[,.(test_text)],paste0(path,"/total_artical.xlsx"))
write_xlsx(data_deal[,1:7],paste0(path,"/artical_background.xlsx"))

```

Step 2.2 處理特殊格式
如"臺灣臺中地方法院 107 年度 勞訴 字第 216 號民事判決（54K）"這篇
並未將分點分項妥善分行。為了後續方便處理，使用



